import sys

from datetime import datetime
from pymongo import Connection
from pymongo.errors import ConnectionFailure
# MongoDB doesn't provide native help with validation so we will need to ensure all types are
# correct and present before insertion
project_documents = [
    {
        #'_id': type 'ObjectId', automatically generated by MongoDB,
        #something like "53d98f133bb604791249ca99"
        'project_version': "1", # I assume this should be a choice of 1 or 2.
        'name': "Portfolio Mockup",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 0, # How should this be set?
        'cohort_id': 0, # How should this be set?
        'author_name': "Cynthia O'Donnell",
        'link': "https://www.github.com",
        'created_date': datetime.datetime.utcnow() # what format do we want?
    },
    {
        'project_version': "1",
        'name': "Portfolio Mockup",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 1,
        'cohort_id': 0,
        'author_name': "Anna Szwemin",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "Portfolio Mockup",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 2,
        'cohort_id': 0,
        'author_name': "James Roeder",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "Portfolio Mockup",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 3,
        'cohort_id': 0,
        'author_name': "Kevin Mayo",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "1",
        'name': "Interactive Resume",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 0,
        'cohort_id': 0,
        'author_name': "Cynthia O'Donnell",
        'link': "https://www.github.com",
        'created_date': datetime.datetime.utcnow()
    },
    {
        'project_version': "1",
        'name': "Interactive Resume",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 1,
        'cohort_id': 0,
        'author_name': "Anna Szwemin",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "Interactive Resume",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 2,
        'cohort_id': 0,
        'author_name': "James Roeder",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "Interactive Resume",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 3,
        'cohort_id': 0,
        'author_name': "Kevin Mayo",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "1",
        'name': "Arcade Game Clone",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 0,
        'cohort_id': 0,
        'author_name': "Cynthia O'Donnell",
        'link': "https://www.github.com",
        'created_date': datetime.datetime.utcnow()
    },
    {
        'project_version': "1",
        'name': "Arcade Game Clone",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 1,
        'cohort_id': 0,
        'author_name': "Anna Szwemin",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "Arcade Game Clone",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 2,
        'cohort_id': 0,
        'author_name': "James Roeder",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "Arcade Game Clone",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 3,
        'cohort_id': 0,
        'author_name': "Kevin Mayo",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "1",
        'name': "Website Optimization",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 0,
        'cohort_id': 0,
        'author_name': "Cynthia O'Donnell",
        'link': "https://www.github.com",
        'created_date': datetime.datetime.utcnow()
    },
    {
        'project_version': "1",
        'name': "Website Optimization",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 1,
        'cohort_id': 0,
        'author_name': "Anna Szwemin",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "Website Optimization",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 2,
        'cohort_id': 0,
        'author_name': "James Roeder",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "Website Optimization",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 3,
        'cohort_id': 0,
        'author_name': "Kevin Mayo",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "1",
        'name': "Neighborhood Map",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 0,
        'cohort_id': 0,
        'author_name': "Cynthia O'Donnell",
        'link': "https://www.github.com",
        'created_date': datetime.datetime.utcnow()
    },
    {
        'project_version': "1",
        'name': "Neighborhood Map",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 1,
        'cohort_id': 0,
        'author_name': "Anna Szwemin",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "Neighborhood Map",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 2,
        'cohort_id': 0,
        'author_name': "James Roeder",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "Neighborhood Map",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 3,
        'cohort_id': 0,
        'author_name': "Kevin Mayo",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "1",
        'name': "JavaScript Testing",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 0,
        'cohort_id': 0,
        'author_name': "Cynthia O'Donnell",
        'link': "https://www.github.com",
        'created_date': datetime.datetime.utcnow()
    },
    {
        'project_version': "1",
        'name': "JavaScript Testing",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 1,
        'cohort_id': 0,
        'author_name': "Anna Szwemin",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "JavaScript Testing",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 2,
        'cohort_id': 0,
        'author_name': "James Roeder",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "JavaScript Testing",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 3,
        'cohort_id': 0,
        'author_name': "Kevin Mayo",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "1",
        'name': "Final Project",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 0,
        'cohort_id': 0,
        'author_name': "Cynthia O'Donnell",
        'link': "https://www.github.com",
        'created_date': datetime.datetime.utcnow()
    },
    {
        'project_version': "1",
        'name': "Final Project",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 1,
        'cohort_id': 0,
        'author_name': "Anna Szwemin",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "Final Project",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 2,
        'cohort_id': 0,
        'author_name': "James Roeder",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    },
    {
        'project_version': "2",
        'name': "Final Project",
        'picture': "http://placekitten.com/200/300",
        'description': "This is my awesome project description.  It is several sentences long.",
        'author_id': 3,
        'cohort_id': 0,
        'author_name': "Kevin Mayo",
        'link': "https://www.github.com",
        'created_date': datetime.datetimeutcnow()
    }
]

def main():
    try:
        c = Connection(host="localhost", port=27017) # default port in MongoDB
    except ConnectionFailure, e:
        sys.stderr.write("Could not connect to MongoDB: %s" % e)
        sys.exit(1)
    dbh = c["mydb"]
    assert dbh.connection == c

    # This creates the 'projects' collection and inserts 'project_doc' to it
    # Be extra careful here, if we misspell 'projects' another collection is created
    # and no error will be thrown
    # We need test coverage for DB insertion to make sure DB name is correct
    dbh.projects.insert(project_documents, safe=True)
    # safe=True ensures that your write will succeed or an exception will be thrown
    print "Successfully inserted documents: %s" % project_documents

if __name__ == "__main__":
    main()
